model_package: Model
root_package: Sample
source: ./test_recipie/test.xmi
templates:
- dest: ./build/test_output{{package.path}}{{package.name}}.jdl
  level: package
  source: entities.jdl
- dest: ./build/test_output{{cls.package.path}}{{cls.name}}.java
  level: class
  source: pojos.java
test_package: Test
test_templates:
- dest: ./build/test_output{{ins.package.path}}/{{ins.stereotype}}.json
  format: json
types:
  boolean: boolean
  date: Date
  dateTime: DateTime
  decimal: Double
  enum: String
  int: int
  integer: int
  long: int
  string: String
